spring.application.name=secure-drive-api

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/securedrive}
spring.datasource.username=${DATABASE_USER:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
jwt.secret=${JWT_SECRET:very-secret-key-very-secret-key-1234}

# GitHub OAuth2
spring.security.oauth2.client.registration.github.client-id=Ov23liC0LMGL7lJwL4mT
spring.security.oauth2.client.registration.github.client-secret=e54cd285ce3f8a33626cb35bee73038ee1d68f8f
spring.security.oauth2.client.registration.github.scope=user:email,read:user


# Swagger/OpenAPI Configuration
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
